topic:
  name: /referee
  type: sentry_msgs/msg/Referee
map_metadata:
  image_path: RMUL2026_场地图片.png
  resolution: 0.01
  width_pixels: 1200
  height_pixels: 800
  origin_pixel:
    - 122.30000000000001
    - 172.3
waypoints:
  - name: 补血点
    pixel:
      - 74.65957446808511
      - 102.12056737588654
    world:
      - -0.476
      - 0.702
  - name: 途径点
    pixel:
      - 133.40425531914894
      - 679.5035460992908
    world:
      - 0.111
      - -5.072
  - name: 巡逻点
    pixel:
      - 509.4326241134752
      - 613.1914893617021
    world:
      - 3.871
      - -4.409
  - name: 占据点
    pixel:
      - 670.2127659574468
      - 455.31914893617017
    world:
      - 5.479
      - -2.83
decision_tree:
  root:
    type: Selector
    children:
      - type: Sequence
        priority: 1
        children:
          - type: Condition
            field: game_progress
            value_type: uint16
            operator: '=='
            threshold: 4
          - type: Condition
            field: current_hp
            value_type: uint16
            operator: <=
            threshold: 150
          - type: Param
            node_name: /serial_interfaces
            param_name: vel_spin
            param_value: '4.0'
            param_type: double
          - type: Param
            node_name: /controller_server
            param_name: FollowPath.translation_kp
            param_value: '4.0'
            param_type: double
          - type: Action
            action: 补血点
            exit_condition:
              field: current_hp
              value_type: uint16
              operator: '>='
              threshold: 400
      - type: Sequence
        priority: 2
        children:
          - type: Condition
            field: game_progress
            value_type: uint16
            operator: '=='
            threshold: 4
          - type: Condition
            field: vision_status
            value_type: uint8
            operator: '=='
            threshold: 1
          - type: Param
            node_name: /serial_interfaces
            param_name: vel_spin
            param_value: '14.0'
            param_type: double
          - type: Param
            node_name: /controller_server
            param_name: FollowPath.translation_kp
            param_value: '3.3'
            param_type: double
          - type: Action
            action: STOP
      - type: Sequence
        priority: 3
        children:
          - type: Condition
            field: game_progress
            value_type: uint16
            operator: '=='
            threshold: 4
          - type: Condition
            field: hp_deduction_reason
            value_type: uint8
            operator: '=='
            threshold: 2741
          - type: Param
            node_name: /serial_interfaces
            param_name: vel_spin
            param_value: '14.0'
            param_type: double
          - type: Param
            node_name: /controller_server
            param_name: FollowPath.translation_kp
            param_value: '4.0'
            param_type: double
          - type: Action
            action: STOP
            duration: 5
      - type: Sequence
        priority: 4
        children:
          - type: Condition
            field: game_progress
            value_type: uint16
            operator: '=='
            threshold: 4
          - type: Condition
            field: stage_remain_time
            value_type: uint16
            operator: '>='
            threshold: 297
          - type: Param
            node_name: /serial_interfaces
            param_name: vel_spin
            param_value: '4.0'
            param_type: double
          - type: Param
            node_name: /controller_server
            param_name: FollowPath.translation_kp
            param_value: '4.0'
            param_type: double
          - type: Action
            action: 巡逻点
      - type: Sequence
        priority: 5
        children:
          - type: Condition
            field: game_progress
            value_type: uint16
            operator: '=='
            threshold: 4
          - type: Condition
            field: game_progress
            value_type: uint16
            operator: '=='
            threshold: 4
          - type: Param
            node_name: /serial_interfaces
            param_name: vel_spin
            param_value: '4.0'
            param_type: double
          - type: Param
            node_name: /controller_server
            param_name: FollowPath.translation_kp
            param_value: '4.0'
            param_type: double
          - type: Action
            action: 巡逻点
          - type: Param
            node_name: /serial_interfaces
            param_name: vel_spin
            param_value: '12.0'
            param_type: double
          - type: Action
            action: 巡逻点
            actions:
              - 巡逻点
            loop: true